version: '2'

volumes:
  myphp:
networks:
  code-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  mynginx:
    container_name: mynginx
    image: nginx:latest
    restart: always
    ports:
      # 宿主机:容器
      - 80:80
      - 8080:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/var/log/nginx/
      - /System/Volumes/Data/mnt/www:/mnt/www
    depends_on:
      - myphp
    networks: 
      code-network:
       ipv4_address: 172.18.0.2

  myphp:
    container_name: myphp
    image: wuzehui/php-fpm
    restart: always
    ports:
      - 9000:9000
    working_dir: /mnt/www/
    volumes:
      #这里设定 自己电脑宿主机的文件路径所在位置相对路径
      - /System/Volumes/Data/mnt/www:/mnt/www
      - ~/.ssh:/root/.ssh
      - ./data/php/log:/var/log/
      #针对本地要修改php.ini的
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/docker-php-ext-ioncube.ini:/usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini
      - ./php/ioncube_loader_lin_7.2.so:/usr/local/lib/php/extensions/no-debug-non-zts-20170718/ioncube_loader_lin_7.2.so
    networks:
      code-network:
        ipv4_address: 172.18.0.3

  myphp2:
    build: ./php72_new
    container_name: myphp2
    restart: always
    ports:
      - 9100:9100
    working_dir: /mnt/www/
    volumes:
      #这里设定 自己电脑宿主机的文件路径所在位置相对路径
      - /System/Volumes/Data/mnt/www:/mnt/www
      - ~/.ssh:/root/.ssh
      - ./data/php/log:/var/log/
      #针对本地要修改php.ini的
      - ./php72_new/php-fpm.d:/usr/local/etc/php-fpm.d
    networks:
      code-network:
        ipv4_address: 172.18.0.13

  myredis:
    container_name: myredis
    image: redis:4.0
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      code-network:
        ipv4_address: 172.18.0.4

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      code-network:
        ipv4_address: 172.18.0.5

  wms_vm:
    build: ./wms_vm
    container_name: wms_vm
    restart: always
    ports:
      - 8090:8080
    volumes:
      - /System/Volumes/Data/mnt/www:/mnt/www
      - ./wms_vm/st_api_gw.json:/etc/st_api_gw.json
    extra_hosts:
      - "wms-api.opskitchen.com:172.18.0.2"
      - "wms-upload.opskitchen.com:172.18.0.2"
    networks:
      code-network:
        ipv4_address: 172.18.0.6