version: '2'

volumes:
  myphp:
networks:
  code-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  mynginx:
    container_name: mynginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/var/log/nginx/
      - myphp:/mnt/www
    volumes_from:
      - myphp
    #外部链接容器方法，用于连接手动创建、别的compose创建
    #external_links:
    #  - mybiweb
    #mem_limit: 200m
    depends_on:
      - myphp
    networks: 
      code-network:
       ipv4_address: 172.18.0.2

  myphp:
    container_name: myphp
    image: flashexpress/php
    restart: always
    ports:
      - 9000:9000
      - 9002:9002
      - 9004:9004
      - 9008:9008
    # expose:
    #   - "9000"
    #   - "19001"
    working_dir: /mnt/www/
    volumes:
      - myphp:/mnt/www
      #这里设定 自己电脑宿主机的文件路径所在位置相对路径
      - /data/www:/data/www
      - ../bi:/mnt/www/bi.flashexpress.com
      - ../backyard:/mnt/www/backyard.flashexpress.com
      - ~/.ssh:/root/.ssh
      - ./data/php/log:/var/log/
      #针对本地要修改php.ini的
      - ./php72/php-fpm.d:/usr/local/etc/php-fpm.d
    #mem_limit: 2000m
    extra_hosts:
      bi.test.fe.com: 192.168.0.230
    networks:

      code-network:
        ipv4_address: 172.18.0.3

  myphp2:
    build: ./php72_new
    container_name: myphp2
    restart: always
    ports:
      - 9100:9100
    working_dir: /mnt/www/
    volumes:
      - myphp:/mnt/www
      #这里设定 自己电脑宿主机的文件路径所在位置相对路径
      - /data/www:/data/www
      - ~/.ssh:/root/.ssh
      - ./data/php/log:/var/log/
      #针对本地要修改php.ini的
      - ./php72/php-fpm.d:/usr/local/etc/php-fpm.d
    networks:
      code-network:
        ipv4_address: 172.18.0.13

  myredis:
    container_name: myredis
    image: redis:4.0
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    #mem_limit: 200m
    networks:
      code-network:
        ipv4_address: 172.18.0.4

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      code-network:
        ipv4_address: 172.18.0.5