version: '3'
services:
  mynginx:
    container_name: mynginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/var/log/nginx/
      - myphp:/mnt/www:rw
    #外部链接容器方法，用于连接手动创建、别的compose创建
    #external_links:
    #  - mybiweb
    #mem_limit: 200m
    networks: 
     - code-network
  myphp:
    container_name: myphp
    image: flashexpress/php
    # build: ./php72
    restart: always
    ports:
      - 9000:9000
    # expose:
    #   - "9000"
    #   - "19001"
    volumes:
      #这里设定 自己电脑宿主机的文件路径所在位置相对路径
      - ../flash/bi:/mnt/www/bi.flashexpress.com
      - ../flash/backyard:/mnt/www/backyard.flashexpress.com
      - ~/.ssh:/root/.ssh
      - ./data/php/log:/var/log/
      - myphp:/mnt/www
      #针对本地要修改php.ini的
      #- ./php72/php-fpm.d:/usr/local/etc/php-fpm.d
    #mem_limit: 2000m
    extra_hosts:
      bi.test.fe.com: 192.168.0.230
    networks:
      - code-network
  myredis:
    container_name: myredis
    image: redis:4.0
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    #mem_limit: 200m
    networks:
      - code-network
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
volumes:
  myphp:
