version: '3.5'

volumes:
  #卷轴式绑定
  mydata:
    driver: local
    driver_opts:
      type: none
      #这个是全物理路径
      device: $PWD/..
      o: bind
  mytmp:
networks:
  code-network:
    driver: bridge

services:
  mynginx:
    container_name: mynginx
    image: nginx:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/var/log/nginx/
      # - ../bi:/mnt/www/bi.flashexpress.com
      # - ../backyard:/mnt/www/backyard.flashexpress.com
      - mydata:/mnt/www
      - mytmp:/tmp
    #外部链接容器方法，用于连接手动创建、别的compose创建
    #external_links:
    #  - mybiweb
    #mem_limit: 200m
    deploy:
      mode: global
      replicas: 2  
      update_config:
        order: start-first
    depends_on:
      - myphp
    networks: 
     - code-network
  myphp:
    #container_name: myphp
    image: flashexpress/php
    restart: always
    #ports:
    #  - 9000:9000
    # expose:
    #   - "9000"
    #   - "19001"
    working_dir: /mnt/www/
    volumes:
      #这里设定 自己电脑宿主机的文件路径所在位置相对路径
      - ~/.ssh:/root/.ssh
      - ./data/php/log:/var/log/
      #针对本地要修改php.ini的
      #- ./php72/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - mydata:/mnt/www
      - mytmp:/tmp
      #- /etc/localtime:/etc/localtime:ro # 将主机的时间同步到容器
    deploy:
      update_config:
        order: start-first
    #mem_limit: 2000m
    extra_hosts:
      bi.test.fe.com: 192.168.0.230
    networks:
      - code-network
  myredis:
    container_name: myredis
    image: redis:4.0
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    #mem_limit: 200m
    networks:
      - code-network
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - code-network
