version: "3.8"

networks:
  code-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  mynginx:
    container_name: mynginx
    image: nginx:1.20.2-alpine
    restart: always
    ports:
      - 80:80
      - 8088:8088
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/var/log/nginx/
      - /mnt/www:/mnt/www
    depends_on:
      - myphp
    networks: 
      code-network:
       ipv4_address: 172.18.0.2

  myphp:
    image: wuzehui/php_image:v1.2
    container_name: myphp
    restart: always
    ports:
      - 9000:9000
    working_dir: /mnt/www/
    volumes:
      - /mnt/www:/mnt/www
      - /home/wzh/.ssh:/root/.ssh
      - ./data/php/log:/var/log/
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      code-network:
        ipv4_address: 172.18.0.3
    extra_hosts:
      - "scm-openapi.ffm.com:172.18.0.2"
      - "wms-openapi.ffm.com:172.18.0.2"
      - "boss-openapi.ffm.com:172.18.0.2"
      - "express-openapi.ffm.com:172.18.0.2"
      - "erp-openapi.ffm.com:172.18.0.2"
      - "erp-oms-openapi.ffm.com:172.18.0.2"
      - "erp-wms-openapi.ffm.com:172.18.0.2"
      - "tt.ffm.com:172.18.0.2"

  myphp2:
    image: wuzehui/php_image:v1.4
    container_name: myphp2
    restart: always
    ports:
      - 9001:9000
    working_dir: /mnt/www/
    volumes:
      - /mnt/www:/mnt/www
      - ./data/php/log:/var/log/
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      code-network:
        ipv4_address: 172.18.0.6

  fcphp:
    build:
      context: ./fc
    container_name: fcphp
    restart: always
    ports:
      - 9002:9000
    working_dir: /mnt/www/
    volumes:
      - /mnt/www:/mnt/www
      - /home/wzh/.ssh:/root/.ssh
      - ./data/php/log:/var/log/
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      code-network:
        ipv4_address: 172.18.0.7

  myredis:
    build: ./redis
    container_name: myredis
    restart: always
    volumes:
      - ./data/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      code-network:
        ipv4_address: 172.18.0.4

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    networks:
      code-network:
        ipv4_address: 172.18.0.5
