version: '3'
services:
  myprometheus:
    container_name: myprometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    #volumes: 
    #  - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - code-prom-network
  mygrafana:
    container_name: mygrafana
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - code-prom-network
networks:
  code-prom-network:
    driver: bridge
