global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
alerting:
    alertmanagers:
    - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
        api_version: v1
scrape_configs:
    - job_name: prometheus
        honor_timestamps: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        static_configs:
        - targets:
        - myprometheus:9090
    - job_name: media # 任务名称为media
        scrape_interval: 3s   # 3秒钟收集一次数据
        metrics_path: /api/v1/rrd/metrics  # 收集数据的URI
        scheme: http
        static_configs:   #子项配置
        - targets: 
        - gslb.offcncloud.com:8080 #收集数据的目标主机以及端口