FROM php:7.2-fpm-alpine

#docker build -t flashexpress/php:molten -f Dockerfile-molten .

ENV BUILD_DEPS tzdata \
    linux-headers \
    libzip-dev \
    curl-dev \
    git

RUN sed -i -e "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories \
    && apk add --no-cache $BUILD_DEPS \
    && apk add --no-cache --virtual .persistent-deps \
        libzip \
        #zip \
        unzip \
# user & group
    && addgroup -g 3000 -S app \
    && adduser -u 3000 -S -D -G app app \
# build deps
# timezone
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && docker-php-source extract \
# configure zip, including install build_deps
    && docker-php-ext-configure zip --with-libzip
# phpiredis
RUN curl -fsSL 'https://github.com/redis/hiredis/archive/v0.13.3.tar.gz' -o hiredis.tar.gz \
    && mkdir -p hiredis \
    && tar -xf hiredis.tar.gz -C hiredis --strip-components=1 \
    && rm hiredis.tar.gz \
    && ( \
        cd hiredis \
        && make -j$(nproc) \
        && make install \
    ) \
    && rm -r hiredis \
    && curl -fsSL 'https://github.com/nrk/phpiredis/archive/v1.0.0.tar.gz' -o phpiredis.tar.gz \
    && mkdir -p phpiredis \
    && tar -xf phpiredis.tar.gz -C phpiredis --strip-components=1 \
    && rm phpiredis.tar.gz \
    && ( \
        cd phpiredis \
        && phpize \
        && ./configure --enable-phpiredis \
        && make -j$(nproc) \
        && make install \
    ) \
    && rm -r phpiredis 
# molten
RUN git clone --depth=1 https://github.com/chuan-yun/Molten.git /usr/src/php/ext/molten \
    && docker-php-ext-configure molten --enable-zipkin-header=yes \
# exts
    && docker-php-ext-install -j$(nproc) zip pdo_mysql molten \
    && docker-php-source delete 
# composer
RUN mkdir -p /usr/local/share/composer \
        && curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
        && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --snapshot \
        && rm -f /tmp/composer-setup.* \
    # 配置composer中国全量镜像
    && composer config -g repo.packagist composer https://packagist.phpcomposer.com \
    && apk del $BUILD_DEPS